In [1]:
import xarray as xr
import pandas as pd

from power_perceiver.load_raw.data_sources.raw_nwp_data_source import RawNWPDataSource
from power_perceiver.consts import Location

NWP_ZARR_PATH = "/media/jack/wd_18tb/data/ocf/NWP/UK_Met_Office/UKV/zarr/UKV_intermediate_version_3.zarr"

In [2]:
raw_nwp = RawNWPDataSource(
    zarr_path=NWP_ZARR_PATH,
    roi_height_pixels=4,
    roi_width_pixels=4,
    history_duration=pd.Timedelta(hours=12),
    forecast_duration=pd.Timedelta(hours=12),
    start_date="2020-01-01",
    end_date="2020-12-31",
    y_coarsen=16,
    x_coarsen=16,
    channels=["dswrf", "t", "si10", "prate"],
)

In [3]:
raw_nwp.per_worker_init(worker_id=0, seed=0)

In [4]:
t0_periods = pd.DataFrame(
    [
        {"start_dt": "2020-06-01", "end_dt": "2020-06-02"},
    ]
)
for col_name in t0_periods.columns:
    t0_periods[col_name] = pd.to_datetime(t0_periods[col_name])
raw_nwp.load_subset_into_ram(t0_periods)

In [5]:
xr_example = raw_nwp.get_example(
    t0_datetime_utc="2020-06-01T12:00",
    center_osgb=Location(x=379379.90625, y=583073.0),
)

In [6]:
xr_example

<xarray.DataArray (target_time_utc: 25, channel: 4, y_osgb: 4, x_osgb: 4)>
array([[[[-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198]],

        [[-0.23643686, -0.70873235, -0.3431845 , -0.41232198],
         [-0.25870611, -0.30954643, -0.51019476, -0.70313615],
         [ 0.05577027, -0.15390498, -0.52560866, -0.48333297],
         [ 0.29534265, -0.06351408, -0.48519432, -0.50614968]],

        [[-0.79959045, -1.30359746, -0.94443013, -0.70180888],
         [-0.93079645, -1.10686168, -1.07373037, -1.335556  ],
         [-0.33926993, -0.62381843, -1.04338438, -1.24891604],
         [-0.29089212, -0.51460235, -0.48660191, -1.14952197]],

        [[-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.16616782],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ]]],

...

       [[[-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198]],

        [[-0.1361127 , -0.51419727, -0.21482456, -0.22759242],
         [-0.27158347, -0.24627889, -0.47799225, -0.48065044],
         [-0.0221934 , -0.21506179, -0.57376645, -0.42739524],
         [ 0.07325842, -0.08028445, -0.47830855, -0.67295921]],

        [[-1.18910367, -1.34684404, -0.99471362, -0.89737192],
         [-1.26592152, -1.23088435, -1.27339803, -1.11829647],
         [-0.72936963, -0.99749895, -1.31371277, -1.37528426],
         [-1.32573385, -1.07373037, -1.04441059, -1.33775494]],

        [[-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ]]]])
Coordinates:
  * channel          (channel) <U5 'dswrf' 't' 'si10' 'prate'
    init_time_utc    (target_time_utc) datetime64[ns] 2020-06-01 ... 2020-06-...
    step             (target_time_utc) timedelta64[ns] 00:00:00 ... 12:00:00
  * x_osgb           (x_osgb) float32 3.2e+05 3.52e+05 3.84e+05 4.16e+05
  * y_osgb           (y_osgb) float32 6.32e+05 6e+05 5.68e+05 5.36e+05
  * target_time_utc  (target_time_utc) datetime64[ns] 2020-06-01 ... 2020-06-02
Attributes:
    t0_idx:                  12
    sample_period_duration:  1:00:00

In [7]:
np_example = raw_nwp.to_numpy(xr_example)
np_example

{<BatchKey.nwp: 12>: array([[[[-1.26368198, -1.26368198, -1.26368198, -1.26368198],
          [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
          [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
          [-1.26368198, -1.26368198, -1.26368198, -1.26368198]],
 
         [[-0.23643686, -0.70873235, -0.3431845 , -0.41232198],
          [-0.25870611, -0.30954643, -0.51019476, -0.70313615],
          [ 0.05577027, -0.15390498, -0.52560866, -0.48333297],
          [ 0.29534265, -0.06351408, -0.48519432, -0.50614968]],
 
         [[-0.79959045, -1.30359746, -0.94443013, -0.70180888],
          [-0.93079645, -1.10686168, -1.07373037, -1.335556  ],
          [-0.33926993, -0.62381843, -1.04338438, -1.24891604],
          [-0.29089212, -0.51460235, -0.48660191, -1.14952197]],
 
         [[-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
          [-0.1663299 , -0.1663299 , -0.1663299 , -0.16616782],
          [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
          [

In [8]:
from power_perceiver.consts import BatchKey

np_example[BatchKey.nwp_step]

array([0.        , 0.08333334, 0.16666667, 0.        , 0.08333334,
       0.16666667, 0.        , 0.08333334, 0.16666667, 0.        ,
       0.08333334, 0.16666667, 0.        , 0.08333334, 0.16666667,
       0.25      , 0.33333334, 0.41666666, 0.5       , 0.5833333 ,
       0.6666667 , 0.75      , 0.8333333 , 0.9166667 , 1.        ],
      dtype=float32)

In [13]:
xr_example.resample(target_time_utc="30T").interpolate(kind="cubic")

<xarray.DataArray (target_time_utc: 49, channel: 4, y_osgb: 4, x_osgb: 4)>
array([[[[-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198]],

        [[-0.23643686, -0.70873235, -0.3431845 , -0.41232198],
         [-0.25870611, -0.30954643, -0.51019476, -0.70313615],
         [ 0.05577027, -0.15390498, -0.52560866, -0.48333297],
         [ 0.29534265, -0.06351408, -0.48519432, -0.50614968]],

        [[-0.79959045, -1.30359746, -0.94443013, -0.70180888],
         [-0.93079645, -1.10686168, -1.07373037, -1.335556  ],
         [-0.33926993, -0.62381843, -1.04338438, -1.24891604],
         [-0.29089212, -0.51460235, -0.48660191, -1.14952197]],

        [[-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.16616782],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ]]],

...

       [[[-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198],
         [-1.26368198, -1.26368198, -1.26368198, -1.26368198]],

        [[-0.1361127 , -0.51419727, -0.21482456, -0.22759242],
         [-0.27158347, -0.24627889, -0.47799225, -0.48065044],
         [-0.0221934 , -0.21506179, -0.57376645, -0.42739524],
         [ 0.07325842, -0.08028445, -0.47830855, -0.67295921]],

        [[-1.18910367, -1.34684404, -0.99471362, -0.89737192],
         [-1.26592152, -1.23088435, -1.27339803, -1.11829647],
         [-0.72936963, -0.99749895, -1.31371277, -1.37528426],
         [-1.32573385, -1.07373037, -1.04441059, -1.33775494]],

        [[-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ],
         [-0.1663299 , -0.1663299 , -0.1663299 , -0.1663299 ]]]])
Coordinates:
  * channel          (channel) <U5 'dswrf' 't' 'si10' 'prate'
  * x_osgb           (x_osgb) float32 3.2e+05 3.52e+05 3.84e+05 4.16e+05
  * y_osgb           (y_osgb) float32 6.32e+05 6e+05 5.68e+05 5.36e+05
  * target_time_utc  (target_time_utc) datetime64[ns] 2020-06-01 ... 2020-06-02
Attributes:
    t0_idx:                  12
    sample_period_duration:  1:00:00